### ISSUE TITLE
Destination /etc/sysconfig/iptables does not exist

### ISSUE THREAD

**Issue by darabos** [objectrocket/ansible-hadoop#71]
`bootstrap_static.sh` is failing for me with the `Destination /etc/sysconfig/iptables does not exist` error message on Vagrant with the `bento/centos-6.7` box. Indeed `/etc/sysconfig/iptables` does not exist on this system.

(This Vagrant box is expected to be fairly faithful to the real systems where we would want to deploy Hadoop, possibly with your playbooks.)

**Comment by grierdavid** [comment]
Thank you for letting me know. I can see the draw to use Vagrant, but I haven't done any testing there. I will put add a task list to take a look.

**Comment by grierdavid** [comment]
Hello Darabos,

I'm sorry, but I wanted to let you know that we wont be putting any effort into CentOS 6.x Support.  I have yet to attempt this with a CentOS 7.x Vagrant box. 

If you can help me understand your use case maybe I can assist you with a path forward.

Thank you
