### ISSUE TITLE
Grafana is not supported prior to Ambari 2.2.2

### ISSUE THREAD

**Issue by magglass1** [objectrocket/ansible-hadoop#75]
Grafana is hard coded into the blueprints but it's not supported prior to Ambari 2.2.2.  We should have a conditional to verify that ambari_version is >= 2.2.2 before including METRICS_GRAFANA in the blueprints.

**Comment by grierdavid** [comment]
thanks Mark I will make this a conditional.

**Comment by grierdavid** [comment]
Solved in: https://github.com/rackerlabs/ansible-hadoop/pull/80
